//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintenanceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Web.Views.Maintenance.MaintenanceStrings", typeof(MaintenanceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your sport filter if you cannot find the newly added athlete..
        /// </summary>
        public static string Athlete_AddConfirmation {
            get {
                return ResourceManager.GetString("Athlete_AddConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that if an athlete name is deleted, then all results associated with this name will be lost too. Are you sure to delete this athlete?.
        /// </summary>
        public static string Athlete_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Athlete_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another athlete matching the supplied name and country exists.  Continue adding this athlete?.
        /// </summary>
        public static string Athlete_SaveConfirmation {
            get {
                return ResourceManager.GetString("Athlete_SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Maintenance.
        /// </summary>
        public static string Athletes_PageTitle {
            get {
                return ResourceManager.GetString("Athletes_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletes.
        /// </summary>
        public static string Athletes_ResourceTitle {
            get {
                return ResourceManager.GetString("Athletes_ResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSC.
        /// </summary>
        public static string AthletesGeneralInfo_CSC {
            get {
                return ResourceManager.GetString("AthletesGeneralInfo_CSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the number of items to be exported, it will take several minutes to complete the process. Do you still want to continue?.
        /// </summary>
        public static string ExportExcelTimeLimit {
            get {
                return ResourceManager.GetString("ExportExcelTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your sport filter if you cannot find the newly added IST member..
        /// </summary>
        public static string ISTMember_AddConfirmation {
            get {
                return ResourceManager.GetString("ISTMember_AddConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another IST member matching the supplied name and country exists.  Continue adding this IST member?.
        /// </summary>
        public static string ISTMember_SaveConfirmation {
            get {
                return ResourceManager.GetString("ISTMember_SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Maintenance.
        /// </summary>
        public static string ISTMembers_PageTitle {
            get {
                return ResourceManager.GetString("ISTMembers_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IST Members.
        /// </summary>
        public static string ISTMembers_ResourceTitle {
            get {
                return ResourceManager.GetString("ISTMembers_ResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Benchmark Tier.
        /// </summary>
        public static string MaintainBenchmarks_AddBenchmarkTierButton {
            get {
                return ResourceManager.GetString("MaintainBenchmarks_AddBenchmarkTierButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sport from the left menu..
        /// </summary>
        public static string MaintainBenchmarks_Error_NoSelectedSport {
            get {
                return ResourceManager.GetString("MaintainBenchmarks_Error_NoSelectedSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Benchmark Tier.
        /// </summary>
        public static string MaintainBenchmarks_InsertBenchmark_GroupBoxTitle {
            get {
                return ResourceManager.GetString("MaintainBenchmarks_InsertBenchmark_GroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Maintenance.
        /// </summary>
        public static string MaintainBenchmarks_Title {
            get {
                return ResourceManager.GetString("MaintainBenchmarks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain  Sports.
        /// </summary>
        public static string MaintainSports_Title {
            get {
                return ResourceManager.GetString("MaintainSports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the athlete and assign a sport.
        /// </summary>
        public static string Maintenance_AssignSportAndSave {
            get {
                return ResourceManager.GetString("Maintenance_AssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this athlete to the selected event:.
        /// </summary>
        public static string Maintenance_AssignSportCaption {
            get {
                return ResourceManager.GetString("Maintenance_AssignSportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:  .
        /// </summary>
        public static string Maintenance_AssignSportEvent {
            get {
                return ResourceManager.GetString("Maintenance_AssignSportEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a Sport.
        /// </summary>
        public static string Maintenance_AssignSportTitle {
            get {
                return ResourceManager.GetString("Maintenance_AssignSportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string Maintenance_DefaultDeleteConfirmation {
            get {
                return ResourceManager.GetString("Maintenance_DefaultDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Maintenance_GoToPage {
            get {
                return ResourceManager.GetString("Maintenance_GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page: .
        /// </summary>
        public static string Maintenance_GoToPageCaption {
            get {
                return ResourceManager.GetString("Maintenance_GoToPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To a Specific Page.
        /// </summary>
        public static string Maintenance_GoToPageTitle {
            get {
                return ResourceManager.GetString("Maintenance_GoToPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the athlete but do not assign a sport.
        /// </summary>
        public static string Maintenance_NotAssignSportAndSave {
            get {
                return ResourceManager.GetString("Maintenance_NotAssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this IST member and assign a sport.
        /// </summary>
        public static string MaintenanceIST_AssignSportAndSave {
            get {
                return ResourceManager.GetString("MaintenanceIST_AssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this IST member to the selected sport:.
        /// </summary>
        public static string MaintenanceIST_AssignSportCaption {
            get {
                return ResourceManager.GetString("MaintenanceIST_AssignSportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this IST member but do not assign a sport.
        /// </summary>
        public static string MaintenanceIST_NotAssignSportAndSave {
            get {
                return ResourceManager.GetString("MaintenanceIST_NotAssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this NSO member and assign a sport.
        /// </summary>
        public static string MaintenanceNSO_AssignSportAndSave {
            get {
                return ResourceManager.GetString("MaintenanceNSO_AssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this NSO member to the selected sport:.
        /// </summary>
        public static string MaintenanceNSO_AssignSportCaption {
            get {
                return ResourceManager.GetString("MaintenanceNSO_AssignSportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this NSO member and do not assign a sport.
        /// </summary>
        public static string MaintenanceNSO_NotAssignSportAndSave {
            get {
                return ResourceManager.GetString("MaintenanceNSO_NotAssignSportAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that if a member name is deleted, then all results associated with this name will be lost too. Are you sure to delete this member?.
        /// </summary>
        public static string Member_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Member_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your sport filter if you cannot find the newly added NSO member..
        /// </summary>
        public static string NSOMember_AddConfirmation {
            get {
                return ResourceManager.GetString("NSOMember_AddConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another NSO member matching the supplied name and country exists.  Continue adding this NSO member?.
        /// </summary>
        public static string NSOMember_SaveConfirmation {
            get {
                return ResourceManager.GetString("NSOMember_SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Maintenance.
        /// </summary>
        public static string NSOMembers_PageTitle {
            get {
                return ResourceManager.GetString("NSOMembers_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSO Members.
        /// </summary>
        public static string NSOMembers_ResourceTitle {
            get {
                return ResourceManager.GetString("NSOMembers_ResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Maintenance.
        /// </summary>
        public static string Other_Title {
            get {
                return ResourceManager.GetString("Other_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Resources.
        /// </summary>
        public static string Resources_Title {
            get {
                return ResourceManager.GetString("Resources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Edit button.
        /// </summary>
        public static string ShowHideEdit {
            get {
                return ResourceManager.GetString("ShowHideEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Sports.
        /// </summary>
        public static string Sports_Title {
            get {
                return ResourceManager.GetString("Sports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliates.
        /// </summary>
        public static string Tab_Affiliates {
            get {
                return ResourceManager.GetString("Tab_Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string Tab_Contact {
            get {
                return ResourceManager.GetString("Tab_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Athete Support.
        /// </summary>
        public static string Tab_DAS {
            get {
                return ResourceManager.GetString("Tab_DAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_General {
            get {
                return ResourceManager.GetString("Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Assignment.
        /// </summary>
        public static string Tab_PoolAssignment {
            get {
                return ResourceManager.GetString("Tab_PoolAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Tab_Qualifications {
            get {
                return ResourceManager.GetString("Tab_Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Tab_Results {
            get {
                return ResourceManager.GetString("Tab_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Tab_Sports {
            get {
                return ResourceManager.GetString("Tab_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string WhoAmI_Info {
            get {
                return ResourceManager.GetString("WhoAmI_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string WhoAmI_Title {
            get {
                return ResourceManager.GetString("WhoAmI_Title", resourceCulture);
            }
        }
    }
}
