//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EvaluationsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvaluationsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Web.Views.Evaluations.EvaluationsStrings", typeof(EvaluationsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Action Item.
        /// </summary>
        public static string ActionItems_Title {
            get {
                return ResourceManager.GetString("ActionItems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status:.
        /// </summary>
        public static string ActionItemStatusSelector_Label {
            get {
                return ResourceManager.GetString("ActionItemStatusSelector_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Doesn&apos;t Exist.
        /// </summary>
        public static string EvaluationForm_Error_NoEvaluation {
            get {
                return ResourceManager.GetString("EvaluationForm_Error_NoEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Form.
        /// </summary>
        public static string EvaluationForm_Title {
            get {
                return ResourceManager.GetString("EvaluationForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Practices.
        /// </summary>
        public static string EvalutionForm_BestPractices {
            get {
                return ResourceManager.GetString("EvalutionForm_BestPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Evaluation.
        /// </summary>
        public static string EvalutionForm_ChangeToStatusButton_Close {
            get {
                return ResourceManager.GetString("EvalutionForm_ChangeToStatusButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Initial Evaluation.
        /// </summary>
        public static string EvalutionForm_ChangeToStatusButton_Edit {
            get {
                return ResourceManager.GetString("EvalutionForm_ChangeToStatusButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string EvalutionForm_ChangeToStatusButton_NA {
            get {
                return ResourceManager.GetString("EvalutionForm_ChangeToStatusButton_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Evaluation.
        /// </summary>
        public static string EvalutionForm_ChangeToStatusButton_Submit {
            get {
                return ResourceManager.GetString("EvalutionForm_ChangeToStatusButton_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Items.
        /// </summary>
        public static string EvalutionFormPillar_Button_ActionItem {
            get {
                return ResourceManager.GetString("EvalutionFormPillar_Button_ActionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action Item.
        /// </summary>
        public static string EvalutionFormPillar_Button_AddActionItem {
            get {
                return ResourceManager.GetString("EvalutionFormPillar_Button_AddActionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Practices.
        /// </summary>
        public static string EvalutionFormPillar_Button_BestPractice {
            get {
                return ResourceManager.GetString("EvalutionFormPillar_Button_BestPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluations.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Maintenance.
        /// </summary>
        public static string Maintenance_Title {
            get {
                return ResourceManager.GetString("Maintenance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Questions_CopyButton {
            get {
                return ResourceManager.GetString("Questions_CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluaton Version to Copy To:.
        /// </summary>
        public static string Questions_CopyEvaluationsWindow_Label {
            get {
                return ResourceManager.GetString("Questions_CopyEvaluationsWindow_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This Evaluation will be closed, and all open Action Items for this Evaluation will be closed and re-opened in the new version..
        /// </summary>
        public static string Questions_CopyEvaluationsWindow_Warning {
            get {
                return ResourceManager.GetString("Questions_CopyEvaluationsWindow_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Evaluation {0} {1} to the selected version:.
        /// </summary>
        public static string Questions_CopyEvaluationWindow_Heading {
            get {
                return ResourceManager.GetString("Questions_CopyEvaluationWindow_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Evaluation.
        /// </summary>
        public static string Questions_CopyEvaluationWindow_Title {
            get {
                return ResourceManager.GetString("Questions_CopyEvaluationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Season:.
        /// </summary>
        public static string Questions_CopyVersionWindow_CopyToYearLabel {
            get {
                return ResourceManager.GetString("Questions_CopyVersionWindow_CopyToYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Evaluation Version {0} to the selected season:.
        /// </summary>
        public static string Questions_CopyVersionWindow_GroupBoxTitle {
            get {
                return ResourceManager.GetString("Questions_CopyVersionWindow_GroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Evaluation.
        /// </summary>
        public static string Questions_CopyVersionWindow_SubmitButton {
            get {
                return ResourceManager.GetString("Questions_CopyVersionWindow_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Evaluation Version.
        /// </summary>
        public static string Questions_CopyVersionWindow_Title {
            get {
                return ResourceManager.GetString("Questions_CopyVersionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Questions_Question {
            get {
                return ResourceManager.GetString("Questions_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Version {0} Questions.
        /// </summary>
        public static string Questions_QuestionGridLabel {
            get {
                return ResourceManager.GetString("Questions_QuestionGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Previously Deleted Questions.
        /// </summary>
        public static string Questions_ShowDeleted {
            get {
                return ResourceManager.GetString("Questions_ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance - Evaluation Questions.
        /// </summary>
        public static string Questions_Title {
            get {
                return ResourceManager.GetString("Questions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open / Total Action Items.
        /// </summary>
        public static string Summary_ActionItemsColumnTitle {
            get {
                return ResourceManager.GetString("Summary_ActionItemsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Evaluation.
        /// </summary>
        public static string Summary_AddEvaluationButton {
            get {
                return ResourceManager.GetString("Summary_AddEvaluationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Evaluation {0} for the selected sport:.
        /// </summary>
        public static string Summary_AddEvaluationWindow_GroupBoxTitle {
            get {
                return ResourceManager.GetString("Summary_AddEvaluationWindow_GroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport:.
        /// </summary>
        public static string Summary_AddEvaluationWindow_SportLabel {
            get {
                return ResourceManager.GetString("Summary_AddEvaluationWindow_SportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Evaluation.
        /// </summary>
        public static string Summary_AddEvaluationWindow_SubmitButton {
            get {
                return ResourceManager.GetString("Summary_AddEvaluationWindow_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Evaluation.
        /// </summary>
        public static string Summary_AddEvaluationWindow_Title {
            get {
                return ResourceManager.GetString("Summary_AddEvaluationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Version must be selected..
        /// </summary>
        public static string Summary_Error_NoCopyToVersionSelected {
            get {
                return ResourceManager.GetString("Summary_Error_NoCopyToVersionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Evaluation Versions for the Selected Season.
        /// </summary>
        public static string Summary_Error_NoEvaluation {
            get {
                return ResourceManager.GetString("Summary_Error_NoEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Summary.
        /// </summary>
        public static string Summary_Title {
            get {
                return ResourceManager.GetString("Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Summary_Version {
            get {
                return ResourceManager.GetString("Summary_Version", resourceCulture);
            }
        }
    }
}
