//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTP.Ring.Models.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaintenanceISTMembersLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceISTMembersLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Models.ViewModel.Maintenance.ISTMembers.MaintenanceISTMembersLocalizatio" +
                            "n", typeof(MaintenanceISTMembersLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is Required.
        /// </summary>
        internal static string Error_Required_Description {
            get {
                return ResourceManager.GetString("Error_Required_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        internal static string Error_Required_FirstName {
            get {
                return ResourceManager.GetString("Error_Required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        internal static string Error_Required_LastName {
            get {
                return ResourceManager.GetString("Error_Required_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is Required.
        /// </summary>
        internal static string Error_Required_QualificationTypeId {
            get {
                return ResourceManager.GetString("Error_Required_QualificationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport is Required.
        /// </summary>
        internal static string Error_Required_SportsId {
            get {
                return ResourceManager.GetString("Error_Required_SportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Title_Active {
            get {
                return ResourceManager.GetString("Title_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        internal static string Title_CellPhone {
            get {
                return ResourceManager.GetString("Title_CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Title_Comments {
            get {
                return ResourceManager.GetString("Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Title_CountryId {
            get {
                return ResourceManager.GetString("Title_CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        internal static string Title_CountryName {
            get {
                return ResourceManager.GetString("Title_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Specialty.
        /// </summary>
        internal static string Title_CrossCompetency {
            get {
                return ResourceManager.GetString("Title_CrossCompetency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Title_DateOfBirth {
            get {
                return ResourceManager.GetString("Title_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Title_EMailAddress {
            get {
                return ResourceManager.GetString("Title_EMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Title_GenderId {
            get {
                return ResourceManager.GetString("Title_GenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Name.
        /// </summary>
        internal static string Title_GenderName {
            get {
                return ResourceManager.GetString("Title_GenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Comments.
        /// </summary>
        internal static string Title_HasComments {
            get {
                return ResourceManager.GetString("Title_HasComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        internal static string Title_HomePhone {
            get {
                return ResourceManager.GetString("Title_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown City.
        /// </summary>
        internal static string Title_HometownCity {
            get {
                return ResourceManager.GetString("Title_HometownCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown Country.
        /// </summary>
        internal static string Title_HometownCountryId {
            get {
                return ResourceManager.GetString("Title_HometownCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown Province.
        /// </summary>
        internal static string Title_HometownProvinceId {
            get {
                return ResourceManager.GetString("Title_HometownProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Title_ID {
            get {
                return ResourceManager.GetString("Title_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        internal static string Title_MailingAddress {
            get {
                return ResourceManager.GetString("Title_MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing City.
        /// </summary>
        internal static string Title_MailingCity {
            get {
                return ResourceManager.GetString("Title_MailingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Country.
        /// </summary>
        internal static string Title_MailingCountryId {
            get {
                return ResourceManager.GetString("Title_MailingCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Postal Code.
        /// </summary>
        internal static string Title_MailingPostalCode {
            get {
                return ResourceManager.GetString("Title_MailingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Province.
        /// </summary>
        internal static string Title_MailingProvinceId {
            get {
                return ResourceManager.GetString("Title_MailingProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooled.
        /// </summary>
        internal static string Title_Pooled {
            get {
                return ResourceManager.GetString("Title_Pooled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Title_Primary {
            get {
                return ResourceManager.GetString("Title_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Title_PrimaryCSCId {
            get {
                return ResourceManager.GetString("Title_PrimaryCSCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary CSC.
        /// </summary>
        internal static string Title_PrimaryCscIdLong {
            get {
                return ResourceManager.GetString("Title_PrimaryCscIdLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary CSC Name.
        /// </summary>
        internal static string Title_PrimaryCscName {
            get {
                return ResourceManager.GetString("Title_PrimaryCscName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Title_QualificationTypeId {
            get {
                return ResourceManager.GetString("Title_QualificationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Type Name.
        /// </summary>
        internal static string Title_QualificationTypeName {
            get {
                return ResourceManager.GetString("Title_QualificationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified.
        /// </summary>
        internal static string Title_Qualified {
            get {
                return ResourceManager.GetString("Title_Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource ID.
        /// </summary>
        internal static string Title_ResourceId {
            get {
                return ResourceManager.GetString("Title_ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Resource.
        /// </summary>
        internal static string Title_ResourceIdAssignment {
            get {
                return ResourceManager.GetString("Title_ResourceIdAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Pool.
        /// </summary>
        internal static string Title_ResourceIdPool {
            get {
                return ResourceManager.GetString("Title_ResourceIdPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Qualification Id.
        /// </summary>
        internal static string Title_ResourceQualificationId {
            get {
                return ResourceManager.GetString("Title_ResourceQualificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string Title_ResourceSpecialtyId {
            get {
                return ResourceManager.GetString("Title_ResourceSpecialtyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Specialty Name.
        /// </summary>
        internal static string Title_ResourceSpecialtyName {
            get {
                return ResourceManager.GetString("Title_ResourceSpecialtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Sport Id.
        /// </summary>
        internal static string Title_ResourceSportId {
            get {
                return ResourceManager.GetString("Title_ResourceSportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Title_SecondaryCSCId {
            get {
                return ResourceManager.GetString("Title_SecondaryCSCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Name.
        /// </summary>
        internal static string Title_SkypeName {
            get {
                return ResourceManager.GetString("Title_SkypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string Title_SpecialtyId {
            get {
                return ResourceManager.GetString("Title_SpecialtyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Name.
        /// </summary>
        internal static string Title_SportName {
            get {
                return ResourceManager.GetString("Title_SportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Title_SportsId {
            get {
                return ResourceManager.GetString("Title_SportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        internal static string Title_TBD {
            get {
                return ResourceManager.GetString("Title_TBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string Title_YearId {
            get {
                return ResourceManager.GetString("Title_YearId", resourceCulture);
            }
        }
    }
}
