//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTP.Ring.Models.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportingLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportingLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Models.ViewModel.Reporting.ReportingLocalization", typeof(ReportingLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain $ &apos; &lt; &gt; etc...
        /// </summary>
        public static string Error_Regex_Name_EN {
            get {
                return ResourceManager.GetString("Error_Regex_Name_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name (En) is Required.
        /// </summary>
        public static string Error_Required_ColumnDisplayName_EN {
            get {
                return ResourceManager.GetString("Error_Required_ColumnDisplayName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En) is Required.
        /// </summary>
        public static string Error_Required_ColumnFieldName_EN {
            get {
                return ResourceManager.GetString("Error_Required_ColumnFieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En) is Required.
        /// </summary>
        public static string Error_Required_FieldName_EN {
            get {
                return ResourceManager.GetString("Error_Required_FieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Size is Required.
        /// </summary>
        public static string Error_Required_FiledSize {
            get {
                return ResourceManager.GetString("Error_Required_FiledSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En) is Required.
        /// </summary>
        public static string Error_Required_FilterFieldName_EN {
            get {
                return ResourceManager.GetString("Error_Required_FilterFieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name (En) is Required.
        /// </summary>
        public static string Error_Required_FilterName_EN {
            get {
                return ResourceManager.GetString("Error_Required_FilterName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name (Fr) is Required.
        /// </summary>
        public static string Error_Required_FilterName_FR {
            get {
                return ResourceManager.GetString("Error_Required_FilterName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (En) is Required.
        /// </summary>
        public static string Error_Required_Name_EN {
            get {
                return ResourceManager.GetString("Error_Required_Name_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Fr) is Required.
        /// </summary>
        public static string Error_Required_Name_FR {
            get {
                return ResourceManager.GetString("Error_Required_Name_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation is Required.
        /// </summary>
        public static string Error_Required_ReportAggregation {
            get {
                return ResourceManager.GetString("Error_Required_ReportAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Required.
        /// </summary>
        public static string Error_Required_ReportColumnLevel {
            get {
                return ResourceManager.GetString("Error_Required_ReportColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Level is Required.
        /// </summary>
        public static string Error_Required_ReportGroupLevel {
            get {
                return ResourceManager.GetString("Error_Required_ReportGroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand is Required.
        /// </summary>
        public static string Error_Required_ReportOperand {
            get {
                return ResourceManager.GetString("Error_Required_ReportOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name (En).
        /// </summary>
        public static string Title_ColumnDisplayName_EN {
            get {
                return ResourceManager.GetString("Title_ColumnDisplayName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name (Fr).
        /// </summary>
        public static string Title_ColumnDisplayName_FR {
            get {
                return ResourceManager.GetString("Title_ColumnDisplayName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En).
        /// </summary>
        public static string Title_ColumnFieldName_EN {
            get {
                return ResourceManager.GetString("Title_ColumnFieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (Fr).
        /// </summary>
        public static string Title_ColumnFieldName_FR {
            get {
                return ResourceManager.GetString("Title_ColumnFieldName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Title_Default_EN {
            get {
                return ResourceManager.GetString("Title_Default_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (En).
        /// </summary>
        public static string Title_Description_EN {
            get {
                return ResourceManager.GetString("Title_Description_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Fr).
        /// </summary>
        public static string Title_Description_FR {
            get {
                return ResourceManager.GetString("Title_Description_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Title_Display {
            get {
                return ResourceManager.GetString("Title_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En).
        /// </summary>
        public static string Title_FieldName_EN {
            get {
                return ResourceManager.GetString("Title_FieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (Fr).
        /// </summary>
        public static string Title_FieldName_FR {
            get {
                return ResourceManager.GetString("Title_FieldName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Size.
        /// </summary>
        public static string Title_FieldSize {
            get {
                return ResourceManager.GetString("Title_FieldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (En).
        /// </summary>
        public static string Title_FilterFieldName_EN {
            get {
                return ResourceManager.GetString("Title_FilterFieldName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name (Fr).
        /// </summary>
        public static string Title_FilterFieldName_FR {
            get {
                return ResourceManager.GetString("Title_FilterFieldName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name (En).
        /// </summary>
        public static string Title_FilterName_EN {
            get {
                return ResourceManager.GetString("Title_FilterName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name (Fr).
        /// </summary>
        public static string Title_FilterName_FR {
            get {
                return ResourceManager.GetString("Title_FilterName_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Title_FormatString {
            get {
                return ResourceManager.GetString("Title_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Title_Locked {
            get {
                return ResourceManager.GetString("Title_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (En).
        /// </summary>
        public static string Title_Name_EN {
            get {
                return ResourceManager.GetString("Title_Name_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Fr).
        /// </summary>
        public static string Title_Name_FR {
            get {
                return ResourceManager.GetString("Title_Name_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation.
        /// </summary>
        public static string Title_ReportAggregation {
            get {
                return ResourceManager.GetString("Title_ReportAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Title_ReportCategoryId {
            get {
                return ResourceManager.GetString("Title_ReportCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Title_ReportColumnId {
            get {
                return ResourceManager.GetString("Title_ReportColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Title_ReportColumnLevel {
            get {
                return ResourceManager.GetString("Title_ReportColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Title_ReportFilterId {
            get {
                return ResourceManager.GetString("Title_ReportFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Group ID.
        /// </summary>
        public static string Title_ReportGroupId {
            get {
                return ResourceManager.GetString("Title_ReportGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Level.
        /// </summary>
        public static string Title_ReportGroupLevel {
            get {
                return ResourceManager.GetString("Title_ReportGroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report ID.
        /// </summary>
        public static string Title_ReportId {
            get {
                return ResourceManager.GetString("Title_ReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand.
        /// </summary>
        public static string Title_ReportOperand {
            get {
                return ResourceManager.GetString("Title_ReportOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Title_ReportViewId {
            get {
                return ResourceManager.GetString("Title_ReportViewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Group.
        /// </summary>
        public static string Title_SecurityGroupProfileID {
            get {
                return ResourceManager.GetString("Title_SecurityGroupProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Limited.
        /// </summary>
        public static string Title_SecurityUserSport {
            get {
                return ResourceManager.GetString("Title_SecurityUserSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string Title_SortOrder {
            get {
                return ResourceManager.GetString("Title_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Title_SportId {
            get {
                return ResourceManager.GetString("Title_SportId", resourceCulture);
            }
        }
    }
}
