//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTP.Ring.Models.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintenanceAthletesLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceAthletesLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Models.ViewModel.Maintenance.Athletes.MaintenanceAthletesLocalization", typeof(MaintenanceAthletesLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Required.
        /// </summary>
        public static string Error_Required_AffiliateName {
            get {
                return ResourceManager.GetString("Error_Required_AffiliateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Tier is Required.
        /// </summary>
        public static string Error_Required_BenchmarkTierId {
            get {
                return ResourceManager.GetString("Error_Required_BenchmarkTierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Type is Required.
        /// </summary>
        public static string Error_Required_BenchmarkTypeId {
            get {
                return ResourceManager.GetString("Error_Required_BenchmarkTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition is Required.
        /// </summary>
        public static string Error_Required_CompetitionId {
            get {
                return ResourceManager.GetString("Error_Required_CompetitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is Required.
        /// </summary>
        public static string Error_Required_DirectAthleteSupportCode {
            get {
                return ResourceManager.GetString("Error_Required_DirectAthleteSupportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is Required.
        /// </summary>
        public static string Error_Required_DirectAthleteSupportTypeId {
            get {
                return ResourceManager.GetString("Error_Required_DirectAthleteSupportTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline is Required.
        /// </summary>
        public static string Error_Required_DisciplineId {
            get {
                return ResourceManager.GetString("Error_Required_DisciplineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is Required.
        /// </summary>
        public static string Error_Required_EventId {
            get {
                return ResourceManager.GetString("Error_Required_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string Error_Required_FirstName {
            get {
                return ResourceManager.GetString("Error_Required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string Error_Required_LastName {
            get {
                return ResourceManager.GetString("Error_Required_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is Required.
        /// </summary>
        public static string Error_Required_ResourceClassId {
            get {
                return ResourceManager.GetString("Error_Required_ResourceClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport is Required.
        /// </summary>
        public static string Error_Required_SportsId {
            get {
                return ResourceManager.GetString("Error_Required_SportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string Error_Required_SupportName {
            get {
                return ResourceManager.GetString("Error_Required_SupportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season is Required.
        /// </summary>
        public static string Error_Required_YearId {
            get {
                return ResourceManager.GetString("Error_Required_YearId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaintenanceAthletesLocalization_fr_CA {
            get {
                return ResourceManager.GetString("MaintenanceAthletesLocalization_fr_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MaintenanceAthletesLocalization_fr_CA_Designer {
            get {
                return ResourceManager.GetString("MaintenanceAthletesLocalization_fr_CA_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Title_Active {
            get {
                return ResourceManager.GetString("Title_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Title_AffiliateContact {
            get {
                return ResourceManager.GetString("Title_AffiliateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Title_AffiliateEmail {
            get {
                return ResourceManager.GetString("Title_AffiliateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Title_AffiliateName {
            get {
                return ResourceManager.GetString("Title_AffiliateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Title_AffiliateTypeId {
            get {
                return ResourceManager.GetString("Title_AffiliateTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Type Name.
        /// </summary>
        public static string Title_AffiliateTypeName {
            get {
                return ResourceManager.GetString("Title_AffiliateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Title_Amount {
            get {
                return ResourceManager.GetString("Title_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark.
        /// </summary>
        public static string Title_Benchmark {
            get {
                return ResourceManager.GetString("Title_Benchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Resource Id.
        /// </summary>
        public static string Title_BenchmarkResourceId {
            get {
                return ResourceManager.GetString("Title_BenchmarkResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmarks.
        /// </summary>
        public static string Title_BenchmarksEntered {
            get {
                return ResourceManager.GetString("Title_BenchmarksEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Tier.
        /// </summary>
        public static string Title_BenchmarkTierId {
            get {
                return ResourceManager.GetString("Title_BenchmarkTierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Tier Name.
        /// </summary>
        public static string Title_BenchmarkTierName {
            get {
                return ResourceManager.GetString("Title_BenchmarkTierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Type.
        /// </summary>
        public static string Title_BenchmarkTypeId {
            get {
                return ResourceManager.GetString("Title_BenchmarkTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Type Name.
        /// </summary>
        public static string Title_BenchmarkTypeName {
            get {
                return ResourceManager.GetString("Title_BenchmarkTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Title_Category {
            get {
                return ResourceManager.GetString("Title_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string Title_CellPhone {
            get {
                return ResourceManager.GetString("Title_CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Title_Comments {
            get {
                return ResourceManager.GetString("Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Title_CompetitionDate {
            get {
                return ResourceManager.GetString("Title_CompetitionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition ID.
        /// </summary>
        public static string Title_CompetitionId {
            get {
                return ResourceManager.GetString("Title_CompetitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Title_CompetitionLocation {
            get {
                return ResourceManager.GetString("Title_CompetitionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Title_CompetitionName {
            get {
                return ResourceManager.GetString("Title_CompetitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ID.
        /// </summary>
        public static string Title_CountryId {
            get {
                return ResourceManager.GetString("Title_CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Title_CountryName {
            get {
                return ResourceManager.GetString("Title_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Title_DateOfBirth {
            get {
                return ResourceManager.GetString("Title_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Title_DirectAthleteSupportCode {
            get {
                return ResourceManager.GetString("Title_DirectAthleteSupportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Athlete Support Name.
        /// </summary>
        public static string Title_DirectAthleteSupportName {
            get {
                return ResourceManager.GetString("Title_DirectAthleteSupportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Title_DirectAthleteSupportTypeId {
            get {
                return ResourceManager.GetString("Title_DirectAthleteSupportTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Athlete Support Type Name.
        /// </summary>
        public static string Title_DirectAthleteSupportTypeName {
            get {
                return ResourceManager.GetString("Title_DirectAthleteSupportTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string Title_Discipline {
            get {
                return ResourceManager.GetString("Title_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string Title_DisciplineId {
            get {
                return ResourceManager.GetString("Title_DisciplineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline Name.
        /// </summary>
        public static string Title_DisciplineName {
            get {
                return ResourceManager.GetString("Title_DisciplineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Title_EMailAddress {
            get {
                return ResourceManager.GetString("Title_EMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Coach.
        /// </summary>
        public static string Title_EventCoachId {
            get {
                return ResourceManager.GetString("Title_EventCoachId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Coach Name.
        /// </summary>
        public static string Title_EventCoachName {
            get {
                return ResourceManager.GetString("Title_EventCoachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string Title_EventDate {
            get {
                return ResourceManager.GetString("Title_EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Title_EventId {
            get {
                return ResourceManager.GetString("Title_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string Title_EventName {
            get {
                return ResourceManager.GetString("Title_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Title_FirstName {
            get {
                return ResourceManager.GetString("Title_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Title_Gender {
            get {
                return ResourceManager.GetString("Title_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Title_GenderId {
            get {
                return ResourceManager.GetString("Title_GenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Name.
        /// </summary>
        public static string Title_GenderName {
            get {
                return ResourceManager.GetString("Title_GenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments?.
        /// </summary>
        public static string Title_HasComments {
            get {
                return ResourceManager.GetString("Title_HasComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Title_HomePhone {
            get {
                return ResourceManager.GetString("Title_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown City.
        /// </summary>
        public static string Title_HometownCity {
            get {
                return ResourceManager.GetString("Title_HometownCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown Country.
        /// </summary>
        public static string Title_HometownCountryId {
            get {
                return ResourceManager.GetString("Title_HometownCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hometown Province.
        /// </summary>
        public static string Title_HometownProvinceId {
            get {
                return ResourceManager.GetString("Title_HometownProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Title_IsNew {
            get {
                return ResourceManager.GetString("Title_IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Athlete.
        /// </summary>
        public static string Title_IsNewAthlete {
            get {
                return ResourceManager.GetString("Title_IsNewAthlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Title_LastName {
            get {
                return ResourceManager.GetString("Title_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        public static string Title_MailingAddress {
            get {
                return ResourceManager.GetString("Title_MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing City.
        /// </summary>
        public static string Title_MailingCity {
            get {
                return ResourceManager.GetString("Title_MailingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Country.
        /// </summary>
        public static string Title_MailingCountryId {
            get {
                return ResourceManager.GetString("Title_MailingCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Postal Code.
        /// </summary>
        public static string Title_MailingPostalCode {
            get {
                return ResourceManager.GetString("Title_MailingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Province.
        /// </summary>
        public static string Title_MailingProvinceId {
            get {
                return ResourceManager.GetString("Title_MailingProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSO Value.
        /// </summary>
        public static string Title_NSOValue {
            get {
                return ResourceManager.GetString("Title_NSOValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Value.
        /// </summary>
        public static string Title_OTPValue {
            get {
                return ResourceManager.GetString("Title_OTPValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Time.
        /// </summary>
        public static string Title_PerfTime {
            get {
                return ResourceManager.GetString("Title_PerfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Value.
        /// </summary>
        public static string Title_PerfValue {
            get {
                return ResourceManager.GetString("Title_PerfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Coach.
        /// </summary>
        public static string Title_PersonalCoachId {
            get {
                return ResourceManager.GetString("Title_PersonalCoachId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Coach Name.
        /// </summary>
        public static string Title_PersonalCoachName {
            get {
                return ResourceManager.GetString("Title_PersonalCoachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooled.
        /// </summary>
        public static string Title_Pooled {
            get {
                return ResourceManager.GetString("Title_Pooled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Title_Position {
            get {
                return ResourceManager.GetString("Title_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Title_PrimaryCSCId {
            get {
                return ResourceManager.GetString("Title_PrimaryCSCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Affiliate Id.
        /// </summary>
        public static string Title_ResourceAffiliateId {
            get {
                return ResourceManager.GetString("Title_ResourceAffiliateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Title_ResourceClassId {
            get {
                return ResourceManager.GetString("Title_ResourceClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Title_ResourceClassName {
            get {
                return ResourceManager.GetString("Title_ResourceClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Direct Athlete Support Id.
        /// </summary>
        public static string Title_ResourceDirectAthleteSupportId {
            get {
                return ResourceManager.GetString("Title_ResourceDirectAthleteSupportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource ID.
        /// </summary>
        public static string Title_ResourceId {
            get {
                return ResourceManager.GetString("Title_ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Title_ResourceIdShort {
            get {
                return ResourceManager.GetString("Title_ResourceIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Title_ResourceSpecialtyId {
            get {
                return ResourceManager.GetString("Title_ResourceSpecialtyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Specialty Name.
        /// </summary>
        public static string Title_ResourceSpecialtyName {
            get {
                return ResourceManager.GetString("Title_ResourceSpecialtyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Sport Id.
        /// </summary>
        public static string Title_ResourceSportId {
            get {
                return ResourceManager.GetString("Title_ResourceSportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result ID.
        /// </summary>
        public static string Title_ResultId {
            get {
                return ResourceManager.GetString("Title_ResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Title_SecondaryCSCId {
            get {
                return ResourceManager.GetString("Title_SecondaryCSCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Name.
        /// </summary>
        public static string Title_SkypeName {
            get {
                return ResourceManager.GetString("Title_SkypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Title_SportName {
            get {
                return ResourceManager.GetString("Title_SportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Title_SportsId {
            get {
                return ResourceManager.GetString("Title_SportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport TR.
        /// </summary>
        public static string Title_SportTrackingRef {
            get {
                return ResourceManager.GetString("Title_SportTrackingRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Title_SupportContact {
            get {
                return ResourceManager.GetString("Title_SupportContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Title_SupportEmail {
            get {
                return ResourceManager.GetString("Title_SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Title_SupportName {
            get {
                return ResourceManager.GetString("Title_SupportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBD.
        /// </summary>
        public static string Title_TBD {
            get {
                return ResourceManager.GetString("Title_TBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year From.
        /// </summary>
        public static string Title_YearFromId {
            get {
                return ResourceManager.GetString("Title_YearFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Title_YearId {
            get {
                return ResourceManager.GetString("Title_YearId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year To.
        /// </summary>
        public static string Title_YearToId {
            get {
                return ResourceManager.GetString("Title_YearToId", resourceCulture);
            }
        }
    }
}
