//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FundingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FundingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTP.Ring.Web.Views.Funding.FundingStrings", typeof(FundingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Action Item.
        /// </summary>
        public static string ActionItems_Title {
            get {
                return ResourceManager.GetString("ActionItems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status:.
        /// </summary>
        public static string ActionItemStatusSelector_Status {
            get {
                return ResourceManager.GetString("ActionItemStatusSelector_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Funding.
        /// </summary>
        public static string FundingAllocation_SectionName {
            get {
                return ResourceManager.GetString("FundingAllocation_SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string FundingAllocation_Total {
            get {
                return ResourceManager.GetString("FundingAllocation_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated:.
        /// </summary>
        public static string FundingAllocation_Unallocated {
            get {
                return ResourceManager.GetString("FundingAllocation_Unallocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string FundingAllocation_UpdateButton {
            get {
                return ResourceManager.GetString("FundingAllocation_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Sum of all allocated funds can&apos;t exceed Final Recommendation..
        /// </summary>
        public static string FundingGrid_Error_SaveDetailFinalRecmd {
            get {
                return ResourceManager.GetString("FundingGrid_Error_SaveDetailFinalRecmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Resource is required, please select a resource..
        /// </summary>
        public static string FundingGrid_Error_SaveDetailMissingResource {
            get {
                return ResourceManager.GetString("FundingGrid_Error_SaveDetailMissingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Sum of all allocated funds can&apos;t exceed Revising..
        /// </summary>
        public static string FundingGrid_Error_SaveDetailRevising {
            get {
                return ResourceManager.GetString("FundingGrid_Error_SaveDetailRevising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Sum of all fund channels can&apos;t exceed Total Funds..
        /// </summary>
        public static string FundingGrid_Error_SaveDetailTotalFunds {
            get {
                return ResourceManager.GetString("FundingGrid_Error_SaveDetailTotalFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Items.
        /// </summary>
        public static string FundingStatus_Button_ActionItem {
            get {
                return ResourceManager.GetString("FundingStatus_Button_ActionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Actual.
        /// </summary>
        public static string FundingStatus_Button_Actual {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action Item.
        /// </summary>
        public static string FundingStatus_Button_AddActionItem {
            get {
                return ResourceManager.GetString("FundingStatus_Button_AddActionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Funding.
        /// </summary>
        public static string FundingStatus_Button_Close {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Final Recmd.
        /// </summary>
        public static string FundingStatus_Button_Final {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit HPA Recmd.
        /// </summary>
        public static string FundingStatus_Button_Hpa {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Hpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Funding.
        /// </summary>
        public static string FundingStatus_Button_Lock {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string FundingStatus_Button_NA {
            get {
                return ResourceManager.GetString("FundingStatus_Button_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Request.
        /// </summary>
        public static string FundingStatus_Button_New {
            get {
                return ResourceManager.GetString("FundingStatus_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit OTP Recmd.
        /// </summary>
        public static string FundingStatus_Button_Otp {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Request.
        /// </summary>
        public static string FundingStatus_Button_Request {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string FundingStatus_Button_Resource {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Revision.
        /// </summary>
        public static string FundingStatus_Button_Revision {
            get {
                return ResourceManager.GetString("FundingStatus_Button_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Funding Summary exists for selected Sport/National Sport Organization and Season..
        /// </summary>
        public static string Recommendation_Error_NoSelectedSport {
            get {
                return ResourceManager.GetString("Recommendation_Error_NoSelectedSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Recommendations.
        /// </summary>
        public static string Recommendation_Title {
            get {
                return ResourceManager.GetString("Recommendation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Funding Request exists for selected Sport/National Sport Organization and Season..
        /// </summary>
        public static string Requests_Error_NoSelectedSport {
            get {
                return ResourceManager.GetString("Requests_Error_NoSelectedSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Requests.
        /// </summary>
        public static string Requests_Title {
            get {
                return ResourceManager.GetString("Requests_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Funding Request exists for selected Sport/National Sport Organization and Season..
        /// </summary>
        public static string RevisionActual_Error_NoSelectedSport {
            get {
                return ResourceManager.GetString("RevisionActual_Error_NoSelectedSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Revisions/Actuals.
        /// </summary>
        public static string RevisionActual_Title {
            get {
                return ResourceManager.GetString("RevisionActual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Summary_Button_Copy {
            get {
                return ResourceManager.GetString("Summary_Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Summary_Button_New {
            get {
                return ResourceManager.GetString("Summary_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Summary_Create {
            get {
                return ResourceManager.GetString("Summary_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Funding Request.
        /// </summary>
        public static string Summary_CreateFundingWindow_Title {
            get {
                return ResourceManager.GetString("Summary_CreateFundingWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot create the Funding Request. A Funding on the same year, and same sport/organization already exists..
        /// </summary>
        public static string Summary_Error_DuplicateFunding {
            get {
                return ResourceManager.GetString("Summary_Error_DuplicateFunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sport at Season or Sport level from the left menu..
        /// </summary>
        public static string Summary_Error_NoSelectedSport {
            get {
                return ResourceManager.GetString("Summary_Error_NoSelectedSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Request:.
        /// </summary>
        public static string Summary_FundingRequest {
            get {
                return ResourceManager.GetString("Summary_FundingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSC:.
        /// </summary>
        public static string Summary_NewFunding_CSC {
            get {
                return ResourceManager.GetString("Summary_NewFunding_CSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OTP Special Project:.
        /// </summary>
        public static string Summary_NewFunding_OTP {
            get {
                return ResourceManager.GetString("Summary_NewFunding_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Season:.
        /// </summary>
        public static string Summary_NewFunding_Season {
            get {
                return ResourceManager.GetString("Summary_NewFunding_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sport:.
        /// </summary>
        public static string Summary_NewFunding_Sport {
            get {
                return ResourceManager.GetString("Summary_NewFunding_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Summary.
        /// </summary>
        public static string Summary_Title {
            get {
                return ResourceManager.GetString("Summary_Title", resourceCulture);
            }
        }
    }
}
